# ChatLimit v1.3.0 Configuration
# プレイヤー名: %player
# NGワード: %word

# チャットでのprefixを設定します
# カラーコードが使用可能です
# 表示形式: prefix » message
message:
  prefix: "&c&lChatLimit"

# チャットの設定
Chat:
  Enabled: true
  Cancel:
    Enabled: true
  Kick:
    Enabled: true
    Reason: "あなたはきっくされました！"
  SendToOP:
    Enabled: true
    Notice: "&d%player &rがNGワードを発言しました"
  SendToConsole:
    Enabled: true
    Notice: "&d%player &rがNGワード &e%word &rを発言しました"

Command:
  Enabled: true
  Cancel:
    Enabled: true
  Kick:
    Enabled: true
    Reason: "あなたはきっくされました！"
  SendToOP:
    Enabled: true
    Notice: "&d%player &rがNGコマンドを実行しました"
  SendToConsole:
    Enabled: true
    Notice: "&d%player &rがNGコマンド &e%command &rを実行しました"