name: ChatLimit
version: 1.3.0
main: com.github.albardoo02.ChatLimit
api-version: 1.15
authors: [ albardoo02 ]
description: チャット制限プラグイン
website: https://github.com/albardoo02/ChatLimit

commands:
  chatlimit:
    description: ChatLimitコマンド
    aliases:
      - chat
      - limit
      - cl
      - chatl
      - climit

permissions:
  ChatLimit.*:
    children:
      ChatLimit.chat.bypass: true
      ChatLimit.command.bypass: true
      ChatLimit.command.help: true
      ChatLimit.command.version: true
      ChatLimit.command.reload: true
    description: ChatLimitの全権限
    default: op
  ChatLimit.chat.bypass:
    description: チャット制限回避
    default: op
  ChatLimit.command.bypass:
    description: コマンド制限回避
    default: op
  ChatLimit.command.help:
    description: helpコマンド
    default: op
  ChatLimit.command.version:
    description: versionコマンド
    default: op
  ChatLimit.command.reload:
    description: reloadコマンド
    default: op
